Add a first behavioral test
mob-programming-meetup/cloud-desktop pull request #5
Opened 2021-09-08 20:41 UTC by koushik-ms

Contribution from the Mob Programming OSS Meetup session held on the 8th of September 2021.

2021-10-07 23:04 UTC, haraldreingruber requested changes
Thanks a lot, everybody for this contribution, I really like the approach you took. 🎉

Right now I am getting a `UnhandledPromiseRejectionWarning: Error: Invalid value for field 'resource.disks': ''. No disks are specified.` when running the command on this branch.

If the idea is to add more tests and step by step making it work again that's fine too of course, Otherwise, it would be great if the previously working behavior could be restored 🙂

Thanks for the great input.

2021-10-07 23:04 UTC, haraldreingruber commented on src/windows-gce-instance.js
> +     } ;
Is this a temporary change that should be reversed, or an intermediate step until all the required tests for this function are added?

2021-10-20 19:10 UTC, koushik-ms commented on src/windows-gce-instance.js
> +     } ;
It was an intermediate step and thanks to the mob from the session on 20.10 we now have a working version that makes it fully working again (with tests passing, of course).

2022-03-22 18:49 UTC, haraldreingruber approved these changes
Better late than never. Thanks for the contribution!

2022-03-22 18:49 UTC, merged